version: '3.8'
services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"


  app-flask:
    build: ./app-flask
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis

  app-node:
    build: ./app-node
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana"
