version: '3.8'

services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - redis-network

  app-flask:
    build: ./app-flask
    container_name: app-flask
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - redis-network
      - app-flask-network

  app-node:
    build: ./app-node
    container_name: app-node
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - redis-network
      - app-node-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - prometheus-network

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - loki-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - grafana-network
      - prometheus-network
      - loki-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - grafana
      - prometheus
    networks:
      - grafana-network
      - prometheus-network
      - app-flask-network
      - app-node-network

volumes:
  grafana-storage:
    driver: local
  prometheus-data:
    driver: local
  loki-data:
    driver: local
  redis-data:
    driver: local
  redis-commander-data:
    driver: local

networks:
  redis-network:
    driver: bridge
  grafana-network:
    driver: bridge
  loki-network:
    driver: bridge
  prometheus-network:
    driver: bridge
  redis-commander-network:
    driver: bridge
  app-flask-network:
    driver: bridge
  app-node-network:
    driver: bridge