global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['app-flask:5000']

  - job_name: 'node-app'
    static_configs:
      - targets: ['app-node:3000']